#! /usr/bin/env bash

set -eu -o pipefail

# Script helps ensure that /etc/hosts has all the correct entries in it

function check_host () {
  host=$1
  host_line=$(grep "$host" /etc/hosts || true)

  if [ -z "${host_line}" ]; then
    # shellcheck disable=SC1117
    echo "127.0.0.1 ${host}" | sudo tee -a /etc/hosts
  fi
}

check_host milmove.daycos.com
check_host office-milmove.daycos.com
check_host orders-milmove.daycos.com
check_host admin-milmove.daycos.com
check_host engadmin-milmove.daycos.com
check_host prime-milmove.daycos.com
